micronaut:
  application:
    name: keyManager

datasources:
  default:
    url: jdbc:mysql://localhost:3306/apidatabase?createDatabaseIfNotExist=true
    username: root
    password: root

jpa:
  default:
    properties:
      hibernate:

        hbm2ddl:
          auto: update
        show_sql: true
